[project]
name = "ai-hedge-fund"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.21"
dependencies = [
    "langchain==0.3.19",
    "langchain-community==0.3.18",
    "langchain-core==0.3.44",
    "python-dotenv"
]
